### ISSUE TITLE
Update Impressum Fields

### ISSUE THREAD

**Issue by Tobias-Conrad** [mapodev/impressum-manager-wordpress#2]
Update Impressum Fields: Was ist dort zu tun?
Gefühlt kann ich dort die Reihenfolge der Texte ändern.
Das will ich aber nicht. Auch weiß ich nicht welche Reihenfolge rechtlich richtig ist!

**Comment by mapodev** [comment]
Beitrag 1848f72734d1537a72ed1e1bcf2da19e1b13a037 hat das Problem gelöst, wo das Preview System nicht funktioniert hat.
