### ISSUE TITLE
Schreibfehler GdR -> GbR

### ISSUE THREAD

**Issue by hendrikschulte** [mapodev/impressum-manager-wordpress#7]
Hallihallo,
bei der Rechtsform hat sich ein Fehler eingeschlichen:
Rechtsform: Gesellschaft bürgerlichen Rechts (GdR)

richtig:
Rechtsform: Gesellschaft bürgerlichen Rechts (GbR)

Vielen Dank, tolles Plugin!

**Comment by mapodev** [comment]
Danke für den Hinweis. Wird heute Abend aktualisiert.

**Comment by mapodev** [comment]
Danke für den Hinweis!
